apps/payments/urls.py
from django.urls import path
from . import views

app_name ='payments'
urlpatterns = [
    path('<int:pk>/check/', views.payment_check, name='payment_check'),
    path('<int:pk>/', views.payment_detail, name='payment_detail'),

    path('payment/', views.pay_home, name='pay_home'),
    path('<int:pk>/subsctiption_pay/', views.subscription_pay, name='subscription_pay'),

    # path('subscribe_payment/<int:pk>/', views.subscribe_payment, name='subscribe_payment'),
    # path('get_customer_uid/<int:pk>/', views.get_customer_uid, name='get_customer_uid'),
    # path('payment_complete/', views.payment_complete, name='payment_complete'),
    path('cancel_schedule_payment/<int:pk>/', views.cancel_schedule_payment, name='cancel_schedule_payment'),
    path('webhook/', views.payment_webhook, name='payment_webhook'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from . import views
from apps.info import views as info_views 

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
    path('', views.home, name='index'),
    path('home/', views.home, name='home'),
    path('contents/', include('apps.contents.urls')),
    path('accounts/', include('apps.accounts.urls')),
    path('chattings/', include('apps.chattings.urls')),
    path('player/noone/', TemplateView.as_view(template_name="info/noone_info_detail.html"), name='noone_info_detail'),
    path('team/<str:info_team_name>/', info_views.team_detail, name='team_detail'),
    path('player/<str:info_player_name>/', info_views.player_detail, name='player_detail'),
    path('subscriptions/', include('apps.subscriptions.urls')),
    path('payments/', include('apps.payments.urls')),
    path('search/', include('apps.search.urls', namespace='search')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/payments/models.py
from django.db import models
from uuid import UUID, uuid4
from django.conf import settings
from iamport import Iamport
import logging
from django.http import Http404
from django.utils.functional import cached_property
from apps.accounts.models import *
from apps.subscriptions.models import SubscriptionPlan, Subscription
from django.utils import timezone
from .services import schedule_payment

logger = logging.getLogger(__name__)


class AbstractPortonePayment(models.Model):
    class StatusChoices(models.TextChoices):
        READY = "ready", "미결제"
        PAID = "paid", "결제완료"
        CANCELLED = "cancelled", "결제취소"
        FAILED = "failed", "결제실패"
    
    meta = models.JSONField("포트원 결제내역", default=dict, editable=False)
    uid = models.UUIDField(default=uuid4, editable=False)
    name = models.CharField(max_length=100)
    amount = models.PositiveIntegerField(editable=False)
    created_at = models.DateTimeField(auto_now_add=True)

    status = models.CharField(
        max_length=9, 
        default=StatusChoices.READY,
        choices=StatusChoices.choices,
        db_index=True,
    )

    is_paid = models.BooleanField("결제성공 여부", default=False, db_index=True)
    
    @property
    def merchant_uid(self):
        return self.uid
    
    @cached_property
    def api(self):
        return Iamport(
            imp_key=settings.PORTONE_API_KEY, imp_secret=settings.PORTONE_API_SECRET
        )
    
    # 결제검증
    def portone_check(self, commit=True):

        try:
            self.meta = self.api.find(merchant_uid=self.merchant_uid)
        except (Iamport.ResponseError, Iamport.HttpError) as e:
            logger.error(str(e), exc_info=e)
            raise Http404("포트원에서 결제내역을 찾을 수 없습니다")
        
        self.status = self.meta['status']
        self.is_paid = self.api.is_paid(self.amount, response=self.meta)

        #TODO : status = PAID인데 is_paid가 False인 경우
        
        if commit:
            self.save()

    class Meta:
        abstract = True


class SubscriptionPayment(AbstractPortonePayment):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='subscription_payments')
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    plan = models.ForeignKey(SubscriptionPlan, on_delete=models.CASCADE)
    customer_uid = models.CharField(max_length=100, editable=False)
    next_merchant_uid = models.CharField(max_length=40, blank=True, null=True)


    @classmethod
    def create_by_payment(cls, player, subscriber, plan_name):
        plan = SubscriptionPlan.objects.get(sub_name=plan_name)
        customer_uid = f"cust_{subscriber.id}"
        payment = cls.objects.create(
            name=f"{player.player_name} 구독권",
            amount=plan.price,
            player=player,
            user = subscriber,
            plan=plan,
            customer_uid=customer_uid,
        )

        return payment

    
    def schedule_next_payment(self, retry=False):
        # 정기결제 결제실패할 시, 하루 뒤 재시도
        if retry:
            schedule_at = float((timezone.now() + timezone.timedelta(days=1)).timestamp())
        else:
            # schedule_at = float((timezone.now() + timezone.timedelta(minutes=2)).timestamp())
            schedule_at = float((timezone.now() + timezone.timedelta(days=self.plan.duration)).timestamp())

        self.next_merchant_uid = uuid.uuid4()
        self.save()

        schedule_payment(
            customer_uid=self.customer_uid,
            merchant_uid=str(self.next_merchant_uid),
            amount=self.amount,
            schedule_at=schedule_at,
            name=f"{self.player.player_name} 구독권",
        )

  
    def create_subscription_if_paid(self):
        if self.is_paid:
            Subscription.objects.create(
                subscriber=self.user,
                subscribed_to_player=self.player,
                plan=self.plan,
                start_date=timezone.now().date(),
            )

            # 결제 성공시에만 다음 결제 예약
            self.schedule_next_payment()

    def save_schedule_payment(self):
        try:

            meta = self.api.find(merchant_uid=self.next_merchant_uid)

            # 예약결제건 결제내역 저장
            payment = SubscriptionPayment.objects.create(
                uid=self.next_merchant_uid,
                player=self.player,
                plan=self.plan,
                customer_uid=self.customer_uid,
                amount=self.amount,
                status = self.meta['status'],
                name=self.name,
                meta=meta,
                user=self.user,
            )

            payment.portone_check(commit=True)

            # 결제 성공시, 구독권 연장
            if self.is_paid:

                subscription = Subscription.objects.filter(
                subscriber=self.user,
                subscribed_to_player=self.player,
                plan=self.plan,
                status=True
                ).first()

                subscription.end_date += timezone.timedelta(days=self.plan.duration)
                subscription.save()


            payment.schedule_next_payment()

        except Exception as e:
            print(f"Error in save_schedule_payment: {str(e)}")
            raise

apps/payments/views.py
import json
from django.contrib import messages
from django.shortcuts import render,redirect,get_object_or_404
from django.urls import reverse
from django.conf import settings
from .models import *
from apps.accounts.models import *
from apps.subscriptions.models import *
from django.http import Http404, HttpResponse, JsonResponse
from django.views.decorators.http import require_POST, require_GET
from .services import *
from django.views.decorators.csrf import csrf_exempt

# Create your views here.

## test 하려고 만든 함수
def pay_home(request):
    players = Player.objects.filter(team__team_name='FC 서울')
    return render(request, 'payments/pay_home.html', 
        {
            'players' : players,
        }
    )


def subscription_pay(request,pk):
    player = Player.objects.get(pk=pk)
    subscriber = request.user

    # #TODO: 유효구독 redicrt 디엠창으로
    # if Subscription.has_active_subscription(subscriber, player):
    #     # messages('현재 유효한 구독이 있습니다. 새로운 구독을 결제할 수 없습니다.')

    #     #### fix: 해당 선수와의 디엠창으로 리다이렉트 ####
    #     # return redirect("payments:payment_detail", pk=pk)
    #     raise Http404("현재 유효한 구독이 있습니다")
    
    payment = SubscriptionPayment.create_by_payment(player, subscriber, 'Basic Plan')

    payment_props = {
        'pg': 'kakaopay',
        'merchant_uid': payment.merchant_uid,
        'name': payment.name,
        'amount': payment.amount,
        'customer_uid': payment.customer_uid,
    }

    payment_check_url = reverse("payments:payment_check", args=[payment.pk])
    
    return render(
        request,
        "payments/payment.html",
        {
            "portone_shop_id": settings.PORTONE_SHOP_ID,
            "payment_props": payment_props,
            "payment_check_url": payment_check_url,
        },
    )

def payment_check(request, pk):
    payment = get_object_or_404(SubscriptionPayment, pk=pk)
    
    # 결제검증
    payment.portone_check()

    # 결제 성공시 구독 등록
    payment.create_subscription_if_paid()

    player_info = {
        'player_name': payment.player.player_name,
        'player_profile_image': payment.player.user.profile.url if payment.player.user.profile else None,
    }
    
    response_data = {
        'is_paid': payment.is_paid,
        'player_info': player_info,
    }
    
    if payment.is_paid:
        subscription = Subscription.objects.filter(
            subscriber=payment.user, 
            subscribed_to_player=payment.player, 
            plan=payment.plan
        ).first()
        if subscription:
            response_data['player_info'].update({
                'subscription_start': subscription.start_date.strftime('%Y-%m-%d'),
                'subscription_end': subscription.end_date.strftime('%Y-%m-%d'),
            })
    
    return JsonResponse(response_data)
    # return redirect("payments:payment_detail", pk=pk")


def payment_detail(request, pk):
    payment = get_object_or_404(SubscriptionPayment, pk=pk)
    return render(
        request, 
        "payments/payment_detail.html",
        {
            "payment" : payment,
        }    
    )

def cancel_schedule_payment(request, pk):
    payment = get_object_or_404(SubscriptionPayment, pk=pk)
    
    try:

        recent_payment = SubscriptionPayment.objects.filter(
            customer_uid=payment.customer_uid,
            player_id=payment.player_id
        ).order_by('-created_at').first()


        # 예약된 결제 취소
        response = cancel_scheduled_payment(recent_payment.customer_uid, recent_payment.next_merchant_uid)
        
        ## rediect로 취소내역 보여주는걸로 수정해야함
        return HttpResponse(f"예약된 결제가 취소되었습니다: {response}", status=200)
    
    except Exception as e:
        return HttpResponse(f"예약 취소 실패: {e}", status=400)


@csrf_exempt
@require_POST
def payment_webhook(request):
    try:
        data = json.loads(request.body)
        merchant_uid = data.get('merchant_uid')
        status = data.get('status')

        print(merchant_uid, status)


        # 정기결제 결제완료
        if status == 'paid':
            try:
                payment = SubscriptionPayment.objects.get(uid=merchant_uid)
                pass
                
            except SubscriptionPayment.DoesNotExist:
                payment = SubscriptionPayment.objects.get(next_merchant_uid=merchant_uid)
                payment.save_schedule_payment()
            

        # 정기결제 결제실패
        elif status == 'failed':
            payment = SubscriptionPayment.objects.get(next_merchant_uid=merchant_uid)
            payment.is_paid = False
            payment.save()

            # 재결제 시도
            payment.schedule_next_payment(retry=True)

        # 관리자가 결제취소
        elif status == 'cancelled':
            payment = SubscriptionPayment.objects.get(uid=merchant_uid)

            payment.is_paid = False
            payment.save()

        else:
            return JsonResponse({'error': 'Invalid status'}, status=400)

        return JsonResponse({'status': 'success'})

    except SubscriptionPayment.DoesNotExist:
        return JsonResponse({'status': 'error', 'message': 'Payment not found'}, status=404)
    except json.JSONDecodeError:
        return JsonResponse({'error': 'Invalid JSON'}, status=400)
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)

templates/payments/pay_home.html
{% extends 'base.html'%}

{% load static %}

{% block extra-style %}

<link rel="stylesheet" href="{% static 'css/payments/payment.css' %}">
<link rel="stylesheet" href="{% static 'css/home.css' %}">

{% endblock extra-style %}

{% block content %}
<div class="player-section">
    <div class="section-title"><h2>구독할 선수를 선택해주세요 !</h2></div>
    {% for player in players %}
        <div class="player-item">
            {% if player.user.profile %}
                <img class="player-image player-trigger" src="{{ player.user.profile.url }}" alt="{{ player.player_name }}'s profile picture"
                     data-player-id="{{ player.id }}" data-player-name="{{ player.player_name }}"
                     data-player-profile="{{ player.user.profile.url }}" data-url="{% url 'payments:subscription_pay' pk=player.id %}">
            {% else %}
                <img class="player-image player-trigger" src="" alt="Default player image"
                     data-player-id="{{ player.id }}" data-player-name="{{ player.player_name }}"
                     data-player-profile="" data-url="{% url 'payments:subscription_pay' pk=player.id %}">
            {% endif %}
            <img class="team-logo" src="{{ player.team.team_picture.url }}" alt="{{ player.team.team_name }}">
            <div class="player-info">
                <p>{{ player.team.team_name }}</p>
                <h3>{{ player.player_name }}</h3>
            </div>
        </div>
    {% endfor %}
</div>
    
    <!-- Modal -->
    <div class="modal" id="playerModal" style="display:none;">
        <div class="modal-content">
            <span class="close">&times;</span>
            <img class="modalPlayerProfile" alt="Player profile picture">
            <div class="modalPlayerName"></div>
            <div class="additional-info">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" fill="none">
                    <circle cx="8" cy="8" r="7.5" stroke="#565E6D"/>
                    <circle cx="8" cy="8" r="4.5" fill="#006600"/>
                </svg>
                <span>월 구독 DM</span>
                <span class="subscription-price">4000원/<span class="highlight">월</span></span>
            </div>
            <div class="notice">
                <div class="notice-title">유의사항</div>
                <ul>
                    <li>구독 기간 동안 플레이어의 메시지를 수신하고, 플레이어에게 메시지를 보낼 수 있습니다.</li>
                    <li>매월 자동으로 정기 결제 되는 상품 입니다. 이용권 금액은 결제 시 결제일로부터 한 달간 서비스를 이용하는 요금이며, 한달 뒤 자동갱신(자동결제) 됩니다.</li>
                    <li>플레이어 비방, 명예훼손, 불안감 조장, 음란성, 사행성, 사칭, 도배, 홍보, 금전/물품 거래, 범죄 조장/방조, 시스템 오류 유발, 기타 서비스 운영 정책 및 법령에 위배되는 내용을 전송한 경우, 메시지 숨김 처리 및 차단 등의 제한 조치가 이루어지며, 해당 사유로 인한 환불은 불가합니다.</li>
                </ul>
            </div>
            <div class="modal-buttons">
                <form id="subscribeForm" method="get">
                    <button type="button" class="cancelButton">취소</button>
                    <button type="submit" id="urlmoveButton">구독하기</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

{% block extra-script %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var modal = document.querySelector('.modal');
        var triggers = document.querySelectorAll('.player-trigger');
        var closeModalButton = document.querySelector('.close');
        var cancelButton = document.querySelector('.cancelButton');
        var subscribeButton = document.getElementById('urlmoveButton');
        var subscribeForm = document.getElementById('subscribeForm');
        
        var modalPlayerName = document.querySelector('.modalPlayerName');
        var modalPlayerProfile = document.querySelector('.modalPlayerProfile');

        modal.style.display = "none";

        triggers.forEach(function(trigger) {
            trigger.addEventListener('click', function() {
                var playerId = this.getAttribute('data-player-id');
                var playerName = this.getAttribute('data-player-name');
                var playerProfile = this.getAttribute('data-player-profile');
                var playerUrl = this.getAttribute('data-url');
                
                modalPlayerName.textContent = playerName;
                // 이미지 존재할 시 띄움
                if (playerProfile) {
                    modalPlayerProfile.src = playerProfile;
                    modalPlayerProfile.style.display = 'block';
                } else {
                    modalPlayerProfile.style.display = 'none';
                }

                modal.style.display = "flex";
                subscribeForm.setAttribute('action', playerUrl);
            });
        });

        closeModalButton.addEventListener('click', function() {
            modal.style.display = "none";
        });

        cancelButton.addEventListener('click', function() {
            modal.style.display = "none";
        });

        subscribeButton.addEventListener('click', function() {
            subscribeForm.submit();
        });

        window.addEventListener('click', function(event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        });
    });
</script>
{% endblock extra-script %}

templates/payments/payment.html
{% load static %}

{% block extra-style %}

<link rel="stylesheet" href="{% static 'css/payments/payment.css' %}">

{% endblock extra-style %}

{% block content %}



{{payment_props|json_script:"payment-props"}}

<script>window.PAYMENT_CHECK_URL = "{{ payment_check_url }}"</script>

<script src="https://cdn.iamport.kr/v1/iamport.js"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
    var cancelButtons = document.querySelectorAll('.cancelButton');
    var retryPaymentButton = document.getElementById('retryPaymentButton');

        function showModal(modalId) {
            document.getElementById(modalId).style.display = 'block';
        }

        function closeModal(modalId) {
            document.getElementById(modalId).style.display = 'none';
        }



        // cancelButtons.forEach(function(button) {
        // button.addEventListener('click', function() {
        //     var modalId = this.closest('.modal').id;
        //     closeModal(modalId);
        //     });
        // });

        // window.addEventListener('click', function(event) {
        //     if (event.target.classList.contains('modal')) {
        //         closeModal(event.target.id);
        //     }
        // });

        cancelButtons.forEach(function(button) {
            button.addEventListener('click', function() {
                window.location.href = "{% url 'home' %}";
            });
        });

        window.addEventListener('click', function(event) {
            if (event.target.classList.contains('modal')) {
                window.location.href = "{% url 'home' %}";
            }
        });


        function updateModalContent(playerInfo, modalType) {
        var modalPlayerName, modalPlayerProfile, modalSubscriptionPeriod;
        if (modalType === 'success') {
            modalPlayerName = document.querySelector('#success-modal .modalPlayerName');
            modalPlayerProfile = document.querySelector('#success-modal .modalPlayerProfile');
            modalSubscriptionPeriod = document.querySelector('#success-modal .modalSubscriptionPeriod');
        } else if (modalType === 'failure') {
            modalPlayerName = document.querySelector('#failure-modal .modalPlayerName');
            modalPlayerProfile = document.querySelector('#failure-modal .modalPlayerProfile');
        }
        modalPlayerName.textContent = playerInfo.player_name;
        if (playerInfo.player_profile_image) {
            modalPlayerProfile.src = playerInfo.player_profile_image;
            modalPlayerProfile.style.display = 'block';
        } else {
            modalPlayerProfile.style.display = 'none';
        }
        if (modalType === 'success' && playerInfo.subscription_start && playerInfo.subscription_end) {
            modalSubscriptionPeriod.textContent = `${playerInfo.subscription_start} - ${playerInfo.subscription_end}`;
        }
    }
        // 포트원 결제 SDK
        const IMP = window.IMP;
        const code = "{{ portone_shop_id }}"; // 가맹점 식별코드
        IMP.init(code);


        const json_string = document.querySelector("#payment-props").textContent;
        const props = JSON.parse(json_string);

        function requestPayment() {
            IMP.request_pay(props, function(response) {
                if (response.success) {
                    // 결제성공
                    axios.get(window.PAYMENT_CHECK_URL)
                        .then(response => {
                            const data = response.data;
                            
                            if (data.is_paid) {
                                updateModalContent(data.player_info, 'success');
                                showModal('success-modal');
                            } else {
                                updateModalContent(data.player_info, 'failure');
                                showModal('failure-modal');
                            }
                        })
                        .catch(error => {
                            updateModalContent({ player_name: '', player_profile_image: '' }, 'failure');
                            showModal('failure-modal');
                        });
                } else {
                    // 결제 실패 시에도 서버에서 선수 정보를 받아옴
                    axios.get(window.PAYMENT_CHECK_URL)
                        .then(response => {
                            const data = response.data;
                            updateModalContent(data.player_info, 'failure');
                            showModal('failure-modal');
                        })
                        .catch(error => {
                            updateModalContent({ player_name: '', player_profile_image: '' }, 'failure');
                            showModal('failure-modal');
                        });
                }
            });
        }

    // 결제 요청
    requestPayment();


    // 재결제시도
    retryPaymentButton.addEventListener('click', function() {
        closeModal('failure-modal');
        requestPayment();
    });


    });
</script>

<!-- 결제성공 모달 -->
<div class="modal" id="success-modal" style="display:none;">
    <div class="modal-content">
        <div class="payment-status">결제완료</div>
        <img class="modalPlayerProfile" alt="Player profile picture">
        <div class="modalPlayerName"></div>
        <div class="modalSubscriptionPeriod"></div>
        <div class="notice">
            <div class="notice-title">유의사항</div>
            <ul>
                <li>구독 기간 동안 플레이어의 메시지를 수신하고, 플레이어에게 메시지를 보낼 수 있습니다.</li>
                <li>매월 자동으로 정기 결제 되는 상품 입니다. 이용권 금액은 결제 시 결제일로부터 한 달간 서비스를 이용하는 요금이며, 한달 뒤 자동갱신(자동결제) 됩니다.</li>
                <li>플레이어 비방, 명예훼손, 불안감 조장, 음란성, 사행성, 사칭, 도배, 홍보, 금전/물품 거래, 범죄 조장/방조, 시스템 오류 유발, 기타 서비스 운영 정책 및 법령에 위배되는 내용을 전송한 경우, 메시지 숨김 처리 및 차단 등의 제한 조치가 이루어지며, 해당 사유로 인한 환불은 불가합니다.</li>
            </ul>
        </div>
        <div class="modal-buttons">
            <button type="button" class="cancelButton">홈으로</button>
            <button type="button" id="urlmoveButton" onclick="">DM 바로가기</button>
        </div>
    </div>
</div>

<!-- 결제실패 모달 -->
<div class="modal" id="failure-modal" style="display:none;">
    <div class="modal-content">
        <div class="payment-status">결제실패</div>
        <img class="modalPlayerProfile" alt="Player profile picture">
        <div class="modalPlayerName"></div>
        <div class="payment-title">결제에 실패했습니다. 다시 시도해주세요</div>
        <div class="notice">
            <ul>
                <li>FANKICK은 K-LEAGUE 팬들을 위한 특별한 서비스이며 선택한 축구선수가 직접 보내는 메시지를 수신할 수 있습니다.</li>
                <li>구독 기간 동안 축구선수와 팬들이 메시지를 주고 받으며 소통할 수 있는 특별한 서비스를 제공합니다.</li>
                <li>구독한 축구선수가 직접 작성한 개성 넘치는 메시지, 사진 등의 다양한 콘텐츠를 프라이빗한 메시지로 받아보세요.</li>
            </ul>
        </div>
        <div class="modal-buttons">
            <button type="button" class="cancelButton">홈으로</button>
            <button type="button" id="retryPaymentButton">결제 다시하기</button>
        </div>

    </div>
</div>

{% endblock content %}

templates/payments/payment_detail.html
{% extends 'base.html' %}

{% block content %}

<h2>결제내역</h2>
{{payment.get_status_display}}
{{payment.merchant_uid}}
{{payment.name}}
{{payment.amount}}
{{payment.is_paid}}
{{payment.created_at}}

<button><a href = "{% url 'payments:cancel_schedule_payment' pk=payment.id %}">예약취소</a></button>

{% endblock content %}