apps/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/step1/', views.signup_step1, name='signup_step1'),
    path('signup/email_check/', views.email_check, name='email_check'), 
    path('signup/step2/', views.signup_step2, name='signup_step2'),
    path('signup/step3/', views.signup_step3, name='signup_step3'),
    path('signup/done/', views.signup_done, name='signup_done'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('update_user_info/', views.update_user_info, name='update_user_info'),
    path('delete_account/', views.delete_account, name='delete_account'),
    path('my_community/', views.my_community_view, name='my_community'),
    path('leave_community/<int:membership_id>/', views.leave_community, name='leave_community'),
    path('my_posts/', views.my_posts_view, name='my_posts'),  
    path('post/<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('my_comments/', views.my_comments_view, name='my_comments'),  
    path('delete_comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
]

apps/chattings/urls.py
from django.urls import path
from . import views

app_name = "chattings"

urlpatterns = [
    path('', views.redirect_to_dm, name='redirect_to_dm'),
]

apps/contents/urls.py
from django.urls import path
from . import views

app_name = "contents"

urlpatterns = [
    path('team/<int:team_id>/player_post_list/', views.PlayerPostListView.as_view(), name='player_post_list'),
    path('team/<int:team_id>/user_post_list/', views.UserPostListView.as_view(), name='user_post_list'),
    path('post_detail/<int:post_id>/', views.post_detail_json, name='post_detail_json'),  # JSON 응답을 위한 URL 패턴 추가
    path('create_post/player/', views.create_post_player, name='create_post_player'),
    path('create_post/user/', views.create_post_user, name='create_post_user'),
    path('team/<int:team_id>/join/', views.join_team, name='join_team'),
    path('post_detail/<int:post_id>/add_comment/', views.add_comment, name='add_comment'),  # add_comment 경로 추가
    path('post_detail/<int:post_id>/add_like/', views.add_like, name='add_like'),  # add_like 경로 추가
    path('comment/<int:comment_id>/add_like/', views.add_like, name='add_like_comment'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from . import views
from apps.info import views as info_views 

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
    path('', views.home, name='index'),
    path('home/', views.home, name='home'),
    path('contents/', include('apps.contents.urls')),
    path('accounts/', include('apps.accounts.urls')),
    path('chattings/', include('apps.chattings.urls')),
    path('player/noone/', TemplateView.as_view(template_name="info/noone_info_detail.html"), name='noone_info_detail'),
    path('team/<str:info_team_name>/', info_views.team_detail, name='team_detail'),
    path('player/<str:info_player_name>/', info_views.player_detail, name='player_detail'),
    path('subscriptions/', include('apps.subscriptions.urls')),
    path('payments/', include('apps.payments.urls')),
    path('search/', include('apps.search.urls', namespace='search')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}Fan Kick{% endblock title %}</title>
    
    {% block extra-style %}{% endblock extra-style %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'images/favicon.png' %}" type="image/png">

</head>


<body>
    <header>
        {% include 'header.html' %}
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>
    <footer>
        {% include 'footer.html' %}
    </footer>

    {% block extra-script %} {% endblock extra-script %}

</body>
</html>

templates/footer.html
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}">
</head>

<body>
<footer class="footer">
    <div class="footer-top"></div>
    <div class="fotter-content">
        <div class="top-section">
            <div class="left-column">
                <div class = "logo">
                    <a href = "#"><img src="{% static 'fankick_logo.png' %}" alt="FANKICK LOGO"></a>
                </div>
            </div>
            <div class="right-column">
                <div class="row">
                    <div class="col-md-6">
                        <h4 class="mb-3 font-weight-bold">Project</h4>
                        <a class="text-decoration-none git-link" href="https://github.com/FanKick/Fan_Kick">
                            <h5>Repository</h5>
                        </a>
                    </div>
                    <div class="col-md-6">
                        <div class="team-member">
                            <h4 class="font-weight-bold">Member</h4>
                            <ul class="list-unstyled">
                                <li class="mb-2">
                                    <a href="https://github.com/hyunsu-1130" class="text-decoration-none git-link">신현수</a>
                                </li>
                                <li class="mb-2">
                                    <a href="https://github.com/parksungjoon0805" class="text-decoration-none git-link">박성준</a>
                                </li>
                                <li class="mb-2">
                                    <a href="https://github.com/iseunglee" class="text-decoration-none git-link">이승희</a>
                                </li>
                                <li class="mb-2">
                                    <a href="https://github.com/heize-lee" class="text-decoration-none git-link">이지현</a>
                                </li>
                                <li class="mb-2">
                                    <a href="https://github.com/chlryddk" class="text-decoration-none git-link">최윤아</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="bottom-section">
            <div class="pt-3 left-column">
                <h4 class="font-weight-bold">FAN KICK</h4>
                <p>축구 팬들이 선수와 직접 소통하고, 자신만의 콘텐츠를 공유하며, 다양한 상품과 이벤트를 즐길 수 있는 커뮤니티 플랫폼</p>
            </div>
            <div class="pt-3 right-column">
                <h4>&nbsp;</h4>
                <p>© 2024 Jewelry Box. All right reserved.</p>
            </div>
        </div>
    </div>
</footer>
</body>

templates/header.html
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}">
</head>

<body>
<header class="header">
    <div class="header-logo">
        <a href="{% url 'index' %}">
            <img src="{% static 'fankick_logo.png' %}" alt="FANKICK LOGO">
        </a>
    </div>

    <div class="header-nav-links">
        {% if user.is_authenticated %}
            {% include 'search/search_bar.html' %}
            
            <!-- Notification Icon -->
            <div class="header-nav-item">
                <div class="header-icon-container">
                    <img src="{% static 'images/notification_icon.svg' %}" alt="Notification Icon">
                </div>
            </div>

            <!-- Profile Icon -->
            <div class="header-nav-item">
                <div class="header-icon-container">
                    <a href="{% url 'accounts:update_user_info' %}">
                        <img src="{% static 'images/profile_icon.svg' %}" alt="Profile Icon">
                    </a>
                </div>
            </div>

            <!-- DM Icon -->
            <div class="header-nav-item header-profile-icon">
                <a href="{% url 'chattings:redirect_to_dm' %}">
                    <img src="{% static 'images/dm_icon.svg' %}" alt="DM Icon">
                </a>
            </div>
            
            <!-- Logout Button -->
            <div class="header-nav-item header-button-container">
                <a href="{% url 'accounts:logout' %}">
                    <div>Log out</div>
                </a>
            </div>
        {% else %}
            <!-- Sign in and Log in Buttons -->
            <div class="header-nav-item header-button-container">
                <a href="{% url 'accounts:signup_step1' %}">
                    <div>Sign in</div>
                </a>
            </div>
            <div class="header-nav-item header-button-container">
                <a href="{% url 'accounts:login' %}">
                    <div>Log in</div>
                </a>
            </div>
        {% endif %}
    </div>
</header>

{% block extra-script %}{% endblock extra-script %}
</body>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block extra-style %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
{% endblock extra-style %}

{% block content %}
<div class="slider" id="team-slider">
    {% for team in teams %}
        <div class="team-image">
            <a href="{% url 'team_detail' info_team_name=team.team_info.info_team_name %}">
                {% if team.team_picture %}
                    <img src="{{ team.team_picture.url }}" alt="{{ team.team_name }}">
                {% else %}
                    <img src="{% static 'images/default-team.png' %}" alt="Default team image">
                {% endif %}
            </a>
        </div>
    {% endfor %}
</div>

{% if user.is_authenticated %}
    <div class="community-section">
        <div class="section-title"><h2>나의 커뮤니티</h2></div>
        {% for membership in memberships %}
            <div class="community-item">
                <a href="{% url 'contents:user_post_list' team_id=membership.team.id %}">
                    {% if membership.team.team_info.team_club_picture %}
                        <img src="{{ membership.team.team_info.team_club_picture.url }}" alt="{{ membership.team.team_name }}">
                    {% else %}
                        <img src="{% static 'images/default-team.png' %}" alt="Default image">
                    {% endif %}
                    <img class="team-logo" src="{{ membership.team.team_picture.url }}" alt="{{ membership.team.team_name }}">
                    <h3>{{ membership.team.team_name }}</h3>
                </a>
            </div>
        {% endfor %}
    </div>
{% endif %}

<div class="player-section">
    <div class="section-title"><h2>새로운 플레이어를 만나보세요!</h2></div>
    {% for player in players %}
        <div class="player-item">
            <a href="{% if player.info.info_player_name %}{% url 'player_detail' info_player_name=player.info.info_player_name %}{% else %}{% url 'noone_info_detail' %}{% endif %}">
                {% if player.user.profile %}
                    <img class="player-image" src="{{ player.user.profile.url }}" alt="{{ player.player_name }}">
                {% else %}
                    <img class="player-image" src="{% static 'images/default-player.png' %}" alt="Default player image">
                {% endif %}
                <img class="team-logo" src="{{ player.team.team_picture.url }}" alt="{{ player.team.team_name }}">
                <div class="player-info">
                    <p>{{ player.team.team_name }}</p>
                    <h3>{{ player.player_name }}</h3>
                </div>
            </a>
        </div>
    {% endfor %}
</div>



{% endblock content %}

{% block extra-script %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>
<script>
    $(document).ready(function(){
        $('#team-slider').slick({
            dots: true,
            infinite: true,
            speed: 500,
            slidesToShow: 3,
            slidesToScroll: 1,
            arrows: true,
        });
    });
</script>
{% endblock extra-script %}